// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPNgrpWx5FrYSkKDgXl8ObeJZM8vF_Kt4',
    appId: '1:1012394598981:web:b4cabdcbabad08cda4792c',
    messagingSenderId: '1012394598981',
    projectId: 'work-app-4bc14',
    authDomain: 'work-app-4bc14.firebaseapp.com',
    storageBucket: 'work-app-4bc14.firebasestorage.app',
    measurementId: 'G-WNDRRN1KFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGR1WhtrS1oTuFXgV8aPaARd3oZjbBPP4',
    appId: '1:1012394598981:android:426ab3dcfebc7f93a4792c',
    messagingSenderId: '1012394598981',
    projectId: 'work-app-4bc14',
    storageBucket: 'work-app-4bc14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7tcjFyvxn_dkXuBj-8TSjW54-cT_ebI',
    appId: '1:1012394598981:ios:9c7bf07f750b3cfea4792c',
    messagingSenderId: '1012394598981',
    projectId: 'work-app-4bc14',
    storageBucket: 'work-app-4bc14.firebasestorage.app',
    iosBundleId: 'com.example.foodLabelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx7tcjFyvxn_dkXuBj-8TSjW54-cT_ebI',
    appId: '1:1012394598981:ios:9c7bf07f750b3cfea4792c',
    messagingSenderId: '1012394598981',
    projectId: 'work-app-4bc14',
    storageBucket: 'work-app-4bc14.firebasestorage.app',
    iosBundleId: 'com.example.foodLabelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPNgrpWx5FrYSkKDgXl8ObeJZM8vF_Kt4',
    appId: '1:1012394598981:web:55b67150ca179f65a4792c',
    messagingSenderId: '1012394598981',
    projectId: 'work-app-4bc14',
    authDomain: 'work-app-4bc14.firebaseapp.com',
    storageBucket: 'work-app-4bc14.firebasestorage.app',
    measurementId: 'G-TF97EEZ8WE',
  );

}